name: Branch Restrictions

on:
  pull_request:
    branches:
      - prd

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Allow only hotfix/* branches to merge into prd
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

          # Allow hotfix/* branches
          if [[ "$SOURCE_BRANCH" =~ ^hotfix\/.+$ ]]; then
            echo "Allowed: hotfix branch detected ($SOURCE_BRANCH)"
            exit 0
          fi

          # Reject all others
          echo "Error: Only hotfix/* branches are allowed to merge into prd. '$SOURCE_BRANCH' is not allowed."
          exit 1
