name: Stg Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: stg

    steps:
      - uses: actions/checkout@v3

      - name: Run a simple command
        run: |
          echo "Hello from GitHub Actions!"
          date
          pwd
          ls -la
